### PR TITLE
Add ability for probot to create a new project card when an issue is created

### PR DESCRIPTION
**Pull request by pholleran**
This PR extends `probot/workflow` to enable the creation of new project cards when an issue is created. Users specify the desired target project and column in the repo's `.probot.js` file like so:

```.createCard({project:'myProject', column:'myColumn'})```

When a user creates a new issue, they see something like the following in the issue thread:

image

and this in their project:

image

/cc @bkeepers @lee-dohm

### CODE REVIEW

**Comment by bkeepers** [comment]
@pholleran this looks great! I added you as a collaborator on this repo, so go ahead and merge when you're ready.

I'm probably not going to be doing much on this plugin for the next couple months, so feel free to lead the charge!

**Comment by pholleran** [comment]
@bkeepers - Thanks! I've got a few other ideas for this I may try out in a bit.

It looks like I still don't have write access to the repo. Can you take a quick 👀 and make sure all is 👌 ?

image

**Comment by bkeepers** [comment]
Weird. Did you accept the invite?

**Comment by pholleran** [comment]
@bkeepers - The invite showed up in my inbox a little after typing that comment. All is good now. :)

**Pull request merged**
